// <auto-generated />
using System;
using AkGaming.Tournaments.Infrastructure.Postgres.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AkGaming.Tournaments.Infrastructure.Postgres.Persistence.Migrations
{
    [DbContext(typeof(TournamentDbContext))]
    [Migration("20260430202847_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.Game", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("LogoAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("LogoAssetId");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("media_assets", (string)null);
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("LastRevisionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LogoAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProfileLink")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("RankRating")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("LogoAssetId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("player_profiles", (string)null);
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.Roster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TournamentRegistrationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TournamentRegistrationId");

                    b.ToTable("rosters", (string)null);
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.RosterPlayerSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PlayerProfileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RosterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SnapshotCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SourcePlayerProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SourcePlayerProfileLastRevisionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("RosterId");

                    b.HasIndex("SourcePlayerProfileId");

                    b.ToTable("roster_player_snapshots", (string)null);
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BannerAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("LogoAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ProfileLink")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("BannerAssetId");

                    b.HasIndex("GameId");

                    b.HasIndex("LogoAssetId");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.TeamInviteKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("RemainingUses")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RevokedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "Key")
                        .IsUnique();

                    b.ToTable("team_invite_keys", (string)null);
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.TeamMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique();

                    b.ToTable("team_memberships", (string)null);
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BannerAssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("LogoAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("RegistrationClosedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RegistrationOpenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("StartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BannerAssetId");

                    b.HasIndex("GameId");

                    b.HasIndex("LogoAssetId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tournaments", (string)null);
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.TournamentInfoSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "SortOrder");

                    b.ToTable("tournament_info_sections", (string)null);
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.TournamentRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveRosterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActiveRosterId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TournamentId", "TeamId")
                        .IsUnique();

                    b.ToTable("tournament_registrations", (string)null);
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.TournamentRegistrationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "SortOrder");

                    b.ToTable("tournament_registration_rules", (string)null);

                    b.HasDiscriminator<string>("RuleType").HasValue("TournamentRegistrationRule");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.MaxPlayerRankRatingRegistrationRule", b =>
                {
                    b.HasBaseType("AkGaming.Tournaments.Domain.Entities.TournamentRegistrationRule");

                    b.HasDiscriminator().HasValue("MaxPlayerRankRating");
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.MaxPlayersPerTeamRegistrationRule", b =>
                {
                    b.HasBaseType("AkGaming.Tournaments.Domain.Entities.TournamentRegistrationRule");

                    b.HasDiscriminator().HasValue("MaxPlayersPerTeam");
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.MaxTeamAverageRankRatingRegistrationRule", b =>
                {
                    b.HasBaseType("AkGaming.Tournaments.Domain.Entities.TournamentRegistrationRule");

                    b.HasDiscriminator().HasValue("MaxTeamAverageRankRating");
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.MinPlayersPerTeamRegistrationRule", b =>
                {
                    b.HasBaseType("AkGaming.Tournaments.Domain.Entities.TournamentRegistrationRule");

                    b.HasDiscriminator().HasValue("MinPlayersPerTeam");
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.Game", b =>
                {
                    b.HasOne("AkGaming.Tournaments.Domain.Entities.MediaAsset", "LogoAsset")
                        .WithMany()
                        .HasForeignKey("LogoAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LogoAsset");
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.PlayerProfile", b =>
                {
                    b.HasOne("AkGaming.Tournaments.Domain.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AkGaming.Tournaments.Domain.Entities.MediaAsset", "LogoAsset")
                        .WithMany()
                        .HasForeignKey("LogoAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AkGaming.Tournaments.Domain.Entities.Team", "Team")
                        .WithMany("GuestPlayerProfiles")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Game");

                    b.Navigation("LogoAsset");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.Roster", b =>
                {
                    b.HasOne("AkGaming.Tournaments.Domain.Entities.TournamentRegistration", "TournamentRegistration")
                        .WithMany("Rosters")
                        .HasForeignKey("TournamentRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TournamentRegistration");
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.RosterPlayerSnapshot", b =>
                {
                    b.HasOne("AkGaming.Tournaments.Domain.Entities.Roster", "Roster")
                        .WithMany("PlayerSnapshots")
                        .HasForeignKey("RosterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AkGaming.Tournaments.Domain.Entities.PlayerProfile", "SourcePlayerProfile")
                        .WithMany()
                        .HasForeignKey("SourcePlayerProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Roster");

                    b.Navigation("SourcePlayerProfile");
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.Team", b =>
                {
                    b.HasOne("AkGaming.Tournaments.Domain.Entities.MediaAsset", "BannerAsset")
                        .WithMany()
                        .HasForeignKey("BannerAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AkGaming.Tournaments.Domain.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AkGaming.Tournaments.Domain.Entities.MediaAsset", "LogoAsset")
                        .WithMany()
                        .HasForeignKey("LogoAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BannerAsset");

                    b.Navigation("Game");

                    b.Navigation("LogoAsset");
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.TeamInviteKey", b =>
                {
                    b.HasOne("AkGaming.Tournaments.Domain.Entities.Team", "Team")
                        .WithMany("InviteKeys")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.TeamMembership", b =>
                {
                    b.HasOne("AkGaming.Tournaments.Domain.Entities.Team", "Team")
                        .WithMany("Memberships")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.Tournament", b =>
                {
                    b.HasOne("AkGaming.Tournaments.Domain.Entities.MediaAsset", "BannerAsset")
                        .WithMany()
                        .HasForeignKey("BannerAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AkGaming.Tournaments.Domain.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AkGaming.Tournaments.Domain.Entities.MediaAsset", "LogoAsset")
                        .WithMany()
                        .HasForeignKey("LogoAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BannerAsset");

                    b.Navigation("Game");

                    b.Navigation("LogoAsset");
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.TournamentInfoSection", b =>
                {
                    b.HasOne("AkGaming.Tournaments.Domain.Entities.Tournament", "Tournament")
                        .WithMany("InfoSections")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.TournamentRegistration", b =>
                {
                    b.HasOne("AkGaming.Tournaments.Domain.Entities.Roster", "ActiveRoster")
                        .WithMany()
                        .HasForeignKey("ActiveRosterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AkGaming.Tournaments.Domain.Entities.Team", "Team")
                        .WithMany("Registrations")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AkGaming.Tournaments.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Registrations")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveRoster");

                    b.Navigation("Team");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.TournamentRegistrationRule", b =>
                {
                    b.HasOne("AkGaming.Tournaments.Domain.Entities.Tournament", "Tournament")
                        .WithMany("RegistrationRules")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.Roster", b =>
                {
                    b.Navigation("PlayerSnapshots");
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.Team", b =>
                {
                    b.Navigation("GuestPlayerProfiles");

                    b.Navigation("InviteKeys");

                    b.Navigation("Memberships");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("InfoSections");

                    b.Navigation("RegistrationRules");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("AkGaming.Tournaments.Domain.Entities.TournamentRegistration", b =>
                {
                    b.Navigation("Rosters");
                });
#pragma warning restore 612, 618
        }
    }
}
