// <auto-generated />
using System;
using AkGaming.Management.Modules.GeneralMeetings.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AkGaming.Management.Modules.GeneralMeetings.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(GeneralMeetingsDbContext))]
    partial class GeneralMeetingsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.AgendaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Minutes")
                        .HasMaxLength(50000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("MeetingId", "ParentId", "Order");

                    b.ToTable("GeneralMeetingAgendaItems", (string)null);
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.AnonymousCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BallotId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Issued")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB");

                    b.Property<bool>("Used")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BallotId", "TokenHash")
                        .IsUnique();

                    b.ToTable("GeneralMeetingAnonymousCredentials", (string)null);
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.AnonymousVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BallotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectionsJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BallotId");

                    b.ToTable("GeneralMeetingAnonymousVotes", (string)null);
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CheckedInAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CheckedOutAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MembershipStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId", "MemberId")
                        .IsUnique();

                    b.ToTable("GeneralMeetingAttendances", (string)null);
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.Ballot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgendaItemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximumSelections")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowResultsWhileOpen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgendaItemId");

                    b.ToTable("GeneralMeetingBallots", (string)null);
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.BallotEntitlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BallotId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CredentialIssued")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BallotId", "MemberId")
                        .IsUnique();

                    b.ToTable("GeneralMeetingBallotEntitlements", (string)null);
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.BallotOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BallotId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BallotId");

                    b.ToTable("GeneralMeetingBallotOptions", (string)null);
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.GeneralMeeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentAgendaItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GeneralMeetings", (string)null);
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.InvitationDispatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DispatchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.ToTable("GeneralMeetingInvitationDispatches", (string)null);
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.MeetingAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId", "OccurredAt");

                    b.ToTable("GeneralMeetingAuditEvents", (string)null);
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.ProtocolRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FinalizedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FinalizedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId", "Revision")
                        .IsUnique();

                    b.ToTable("GeneralMeetingProtocolRevisions", (string)null);
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.AgendaItem", b =>
                {
                    b.HasOne("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.GeneralMeeting", "Meeting")
                        .WithMany("AgendaItems")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.AgendaItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Meeting");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.AnonymousCredential", b =>
                {
                    b.HasOne("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.Ballot", null)
                        .WithMany("Credentials")
                        .HasForeignKey("BallotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.AnonymousVote", b =>
                {
                    b.HasOne("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.Ballot", null)
                        .WithMany("Votes")
                        .HasForeignKey("BallotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.GeneralMeeting", "Meeting")
                        .WithMany("Attendees")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.Ballot", b =>
                {
                    b.HasOne("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.AgendaItem", "AgendaItem")
                        .WithMany("Ballots")
                        .HasForeignKey("AgendaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgendaItem");
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.BallotEntitlement", b =>
                {
                    b.HasOne("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.Ballot", null)
                        .WithMany("Entitlements")
                        .HasForeignKey("BallotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.BallotOption", b =>
                {
                    b.HasOne("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.Ballot", "Ballot")
                        .WithMany("Options")
                        .HasForeignKey("BallotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ballot");
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.InvitationDispatch", b =>
                {
                    b.HasOne("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.GeneralMeeting", null)
                        .WithMany("InvitationDispatches")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.MeetingAuditEvent", b =>
                {
                    b.HasOne("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.GeneralMeeting", null)
                        .WithMany("AuditEvents")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.ProtocolRevision", b =>
                {
                    b.HasOne("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.GeneralMeeting", null)
                        .WithMany("ProtocolRevisions")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.AgendaItem", b =>
                {
                    b.Navigation("Ballots");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.Ballot", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("Entitlements");

                    b.Navigation("Options");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("AkGaming.Management.Modules.GeneralMeetings.Domain.Entities.GeneralMeeting", b =>
                {
                    b.Navigation("AgendaItems");

                    b.Navigation("Attendees");

                    b.Navigation("AuditEvents");

                    b.Navigation("InvitationDispatches");

                    b.Navigation("ProtocolRevisions");
                });
#pragma warning restore 612, 618
        }
    }
}
