FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish AkGaming.Gamenight/WebApi -c Release -o /app/publish -m:1
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://+:8080
ENV Database__Provider=Postgres
ENV DataProtection__KeyDirectory=/app/keys
EXPOSE 8080
ENTRYPOINT ["dotnet", "AkGaming.Gamenight.WebApi.dll"]
