// <auto-generated />
using System;
using AkGaming.Management.Modules.Disbursements.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AkGaming.Management.Modules.Disbursements.Migrations.Postgres.Migrations
{
    [DbContext(typeof(DisbursementsDbContext))]
    [Migration("20260719184028_AddNotificationOutbox")]
    partial class AddNotificationOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AkGaming.Management.Modules.Disbursements.Domain.Entities.Allocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("ShareToken")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ShareToken")
                        .IsUnique();

                    b.ToTable("DisbursementAllocations", (string)null);
                });

            modelBuilder.Entity("AkGaming.Management.Modules.Disbursements.Domain.Entities.AllocationApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllocationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ApplicantUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AllocationId");

                    b.HasIndex("ApplicantUserId");

                    b.ToTable("DisbursementAllocationApplications", (string)null);
                });

            modelBuilder.Entity("AkGaming.Management.Modules.Disbursements.Domain.Entities.AllocationApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApproverName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ApproverUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "ApproverUserId")
                        .IsUnique();

                    b.ToTable("DisbursementAllocationApprovals", (string)null);
                });

            modelBuilder.Entity("AkGaming.Management.Modules.Disbursements.Domain.Entities.DisbursementEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateOnly?>("OccurredOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("DisbursementEvents", (string)null);
                });

            modelBuilder.Entity("AkGaming.Management.Modules.Disbursements.Domain.Entities.ExpenseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly?>("IncurredOn")
                        .HasColumnType("date");

                    b.Property<Guid>("ReimbursementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReimbursementId");

                    b.ToTable("DisbursementExpenseItems", (string)null);
                });

            modelBuilder.Entity("AkGaming.Management.Modules.Disbursements.Domain.Entities.NotificationOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("ProcessedAtUtc", "NextAttemptAtUtc");

                    b.ToTable("DisbursementNotificationOutbox", (string)null);
                });

            modelBuilder.Entity("AkGaming.Management.Modules.Disbursements.Domain.Entities.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ExpenseItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseItemId");

                    b.ToTable("DisbursementReceipts", (string)null);
                });

            modelBuilder.Entity("AkGaming.Management.Modules.Disbursements.Domain.Entities.Reimbursement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdministrativeNote")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DisbursementReimbursements", (string)null);
                });

            modelBuilder.Entity("AkGaming.Management.Modules.Disbursements.Domain.Entities.Allocation", b =>
                {
                    b.HasOne("AkGaming.Management.Modules.Disbursements.Domain.Entities.DisbursementEvent", "Event")
                        .WithMany("Allocations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("AkGaming.Management.Modules.Disbursements.Domain.Entities.AllocationApplication", b =>
                {
                    b.HasOne("AkGaming.Management.Modules.Disbursements.Domain.Entities.Allocation", "Allocation")
                        .WithMany("Applications")
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AkGaming.Management.Modules.Disbursements.Domain.Entities.PaymentMethodSnapshot", "PaymentMethod", b1 =>
                        {
                            b1.Property<Guid>("AllocationApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AccountHolder")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("PaymentMethodAccountHolder");

                            b1.Property<string>("Bic")
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("PaymentMethodBic");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("PaymentMethodDisplayName");

                            b1.Property<string>("Iban")
                                .HasMaxLength(34)
                                .HasColumnType("character varying(34)")
                                .HasColumnName("PaymentMethodIban");

                            b1.Property<string>("PayPalEmail")
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("PaymentMethodPayPalEmail");

                            b1.Property<Guid>("PaymentInformationId")
                                .HasColumnType("uuid")
                                .HasColumnName("PaymentInformationId");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("PaymentMethodType");

                            b1.HasKey("AllocationApplicationId");

                            b1.ToTable("DisbursementAllocationApplications");

                            b1.WithOwner()
                                .HasForeignKey("AllocationApplicationId");
                        });

                    b.Navigation("Allocation");

                    b.Navigation("PaymentMethod")
                        .IsRequired();
                });

            modelBuilder.Entity("AkGaming.Management.Modules.Disbursements.Domain.Entities.AllocationApproval", b =>
                {
                    b.HasOne("AkGaming.Management.Modules.Disbursements.Domain.Entities.AllocationApplication", "Application")
                        .WithMany("Approvals")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("AkGaming.Management.Modules.Disbursements.Domain.Entities.ExpenseItem", b =>
                {
                    b.HasOne("AkGaming.Management.Modules.Disbursements.Domain.Entities.Reimbursement", "Reimbursement")
                        .WithMany("Expenses")
                        .HasForeignKey("ReimbursementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reimbursement");
                });

            modelBuilder.Entity("AkGaming.Management.Modules.Disbursements.Domain.Entities.Receipt", b =>
                {
                    b.HasOne("AkGaming.Management.Modules.Disbursements.Domain.Entities.ExpenseItem", "ExpenseItem")
                        .WithMany("Receipts")
                        .HasForeignKey("ExpenseItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseItem");
                });

            modelBuilder.Entity("AkGaming.Management.Modules.Disbursements.Domain.Entities.Reimbursement", b =>
                {
                    b.OwnsOne("AkGaming.Management.Modules.Disbursements.Domain.Entities.PaymentMethodSnapshot", "PaymentMethod", b1 =>
                        {
                            b1.Property<Guid>("ReimbursementId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AccountHolder")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("PaymentMethodAccountHolder");

                            b1.Property<string>("Bic")
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("PaymentMethodBic");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("PaymentMethodDisplayName");

                            b1.Property<string>("Iban")
                                .HasMaxLength(34)
                                .HasColumnType("character varying(34)")
                                .HasColumnName("PaymentMethodIban");

                            b1.Property<string>("PayPalEmail")
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("PaymentMethodPayPalEmail");

                            b1.Property<Guid>("PaymentInformationId")
                                .HasColumnType("uuid")
                                .HasColumnName("PaymentInformationId");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("PaymentMethodType");

                            b1.HasKey("ReimbursementId");

                            b1.ToTable("DisbursementReimbursements");

                            b1.WithOwner()
                                .HasForeignKey("ReimbursementId");
                        });

                    b.Navigation("PaymentMethod")
                        .IsRequired();
                });

            modelBuilder.Entity("AkGaming.Management.Modules.Disbursements.Domain.Entities.Allocation", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("AkGaming.Management.Modules.Disbursements.Domain.Entities.AllocationApplication", b =>
                {
                    b.Navigation("Approvals");
                });

            modelBuilder.Entity("AkGaming.Management.Modules.Disbursements.Domain.Entities.DisbursementEvent", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("AkGaming.Management.Modules.Disbursements.Domain.Entities.ExpenseItem", b =>
                {
                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("AkGaming.Management.Modules.Disbursements.Domain.Entities.Reimbursement", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
