<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Application\AkGaming.Management.Modules.InvoiceManagement.Application.csproj" />
    <ProjectReference Include="..\Contracts\AkGaming.Management.Modules.InvoiceManagement.Contracts.csproj" />
    <ProjectReference Include="..\Infrastructure\AkGaming.Management.Modules.InvoiceManagement.Infrastructure.csproj" />
  </ItemGroup>
</Project>
